meslekler = [
"Acil Tıp Teknisyeni",
"Adalet Meslek Elemanı",
"Ağaç İşleri Endüstri Mühendisi",
"Ağaç İşleri Teknikeri",
"Ağaç Oymacısı",
"Ahşap Karoserci",
"Aile Ekonomisi ve Beslenme Öğretmeni",
"Aktüer",
"Alçı Dekorasyoncusu",
"Alt Yapı Teknisyeni",
"Alüminyum Doğramacı",
"Ambulans ve Acil Bakım Teknikeri",
"Anahtarcı (Çilingir)",
"Anestezi Teknikeri",
"Anestezi Teknisyeni",
"Animatör",
"Antepfıstığı Teknikeri",
"Argon Kaynakçısı (Tıg Kaynakçısı)",
"Arıcılık Teknikeri",
"Arkeolog",
"Arşivci",
"Asansör Kurucusu ve Bakımcısı",
"Astronom",
"Aşçı",
"Aşçılık",
"Avize İmalatçısı",
"Avrupa Birliği İlişkileri Elemanı",
"Avukat",
"Ayakkabı Teknisyeni",
"Ayakkabı Yapımcısı",
"Ayakkabı, Deri ve Yan Ürünleri Satış Elemanı",
"Şarküteri, Bakkal ve Gıda Pazarları Satış Elemanı",
"Şehir (Kent) Plancısı",
"Bağcılık Teknikeri",
"Bahçe Ziraati Teknikeri",
"Bakım ve Onarım Elektrikçisi",
"Bakırcı",
"Bale Dansçısı",
"Balık Yetiştirme Teknikeri",
"Barmen (Barmaid)",
"Bayan Berberi (Bayan Kuaförü)",
"Beden Eğitimi Öğretmeni",
"Besicilik Teknikeri",
"Besin/Gıda Teknolojisi Yönetimi ve Beslenme Öğretmeni",
"Beton Teknikeri",
"Beton ve Betonarme Kalıpçısı",
"Betonarme Demircisi",
"Bilet Satış Elemanı (Gişe/Banko)",
"Bilgisayar Bakım ve Onarımcısı",
"Bilgisayar Destekli Tasarım Teknikeri",
"Bilgisayar Donanım Teknikeri",
"Bilgisayar Donanım Teknisyeni",
"Bilgisayar Mühendisi",
"Bilgisayar Operatörü",
"Bilgisayar Öğretmeni",
"Bilgisayar Programcısı",
"Bilgisayar Teknolojisi ve Programlama Teknikeri",
"Bilgisayarlı Muhasebe ve Vergi Uygulama Meslek Elemanı",
"Bilgisayarlı Nümeric Kontrol (CNC) Teknisyeni",
"Bitki Koruma Teknikeri",
"Biyokimya Teknikeri",
"Biyokimyager",
"Biyolog",
"Biyoloji Öğretmeni",
"Biyomedikal Cihaz Teknikeri",
"Biyomedikal Mühendisi",
"Biyomühendisi",
"Bobinajcı",
"Borsa Komisyoncusu",
"Borsa ve Finans Meslek Elemanı",
"Boya Teknikeri",
"Boyacı ve Yüzey Hazırlamacı (Yapı)",
"Buldozer Operatörü",
"Büro Makineleri Bakım ve Onarımcısı",
"Büro Yönetimi ve Sekreterlik Meslek Elemanı",
"Cam Mamul İmalatçısı",
"Cam Mamul İşlemecisi (Finitaj)",
"Cerrahi Teknikeri",
"Coğrafya Öğretmeni",
"Coğrafyacı",
"Çalışma Ekonomisti",
"Çanta İmalatçısı ve Saraciyeci",
"Çay Eksperi",
"Çelikhane İşletmecisi",
"Çevre Mühendisi",
"Çevre Sağlığı Teknisyeni",
"Çevre Teknikeri",
"Çiçek, Örgü, Dokuma Öğretmeni",
"Çini İşlemeciliği Teknikeri",
"Çocuk Bakıcısı",
"Çocuk Gelişimi Meslek Elemanı",
"Çocuk Gelişimi ve Eğitimi Öğretmeni",
"Çocuk Giysi Tasarım Teknisyeni",
"Çorap Örme Konfeksiyon Teknisyeni (Çorap Örme Makinesi Operatörü)",
"Daktilograf",
"Dalgıç (Balıkadam)",
"Dekor ve Kostüm Sanatçısı / Tasarımcısı",
"Dekoratif Sanatlar Teknisyeni",
"Deniz Teknolojileri Mühendisi",
"Deniz Ulaştırma İşletme Mühendisi",
"Deniz ve Liman İşletme Meslek Elemanı",
"Denizcilik İşletme Yöneticisi",
"Deri Aksesuarları Teknisyeni",
"Deri İşlemecisi",
"Deri Konfeksiyon Teknikeri",
"Deri Konfeksiyon Teknisyeni",
"Deri Mühendisi",
"Deri Teknikeri",
"Deri Teknisyeni",
"Dış Ticaret Meslek Elemanı",
"Dil Bilimci",
"Din Kültürü ve Ahlak Bilgisi Öğretmeni (İlköğretim)",
"Diplomat (Dış İşleri Meslek Memuru)",
"Diş Hekimi",
"Diş Protez Teknikeri / Ağız ve Diş Sağlığı Teknikeri",
"Diş Protez Teknisyeni",
"Diş Protezcisi",
"Diyaliz Teknikeri",
"Diyetisyen (Beslenme Uzmanı)",
"Dizel Motorları Yakıt Pompası ve Enjektör Ayarcısı",
"Dizgi Teknisyeni",
"Dizgici",
"Doğalgaz Isıtma ve Sıhhi Tesisat Teknikeri",
"Doğalgaz Tesisat Teknisyeni",
"Doğramacı",
"Dokuma Teknisyeni",
"Dokümantasyon ve Enformasyon Elemanı",
"Döküm Öğretmeni",
"Döküm Teknikeri",
"Döküm Teknisyeni",
"Döşeme ve Duvar Kaplamacısı",
"Döşemecilik Teknisyeni",
"Duvar Süsleme Sanatları Teknikeri",
"Duvarcı",
"Ebe",
"Eczacı",
"Ekonometrist",
"Ekonomist",
"Ekskavatör Operatörü",
"El Sanatları Öğretmeni",
"El Sanatları Teknikeri",
"El ve Makine Dikişçisi",
"Elektrik - Elektronik Mühendisi",
"Elektrik Mühendisi",
"Elektrik Öğretmeni",
"Elektrik Teknikeri",
"Elektrik Teknisyeni",
"Elektrik Tesisatçısı",
"Elektrik ve Elektronik Malzemeleri Satış Elemanı",
"Elektrikli Ev Aletleri Bakım ve Tamircisi",
"Elektro Mekanik Taşıyıcılar Teknisyeni",
"Elektronik / Telekomünikasyon Öğretmeni",
"Elektronik Mühendisi",
"Elektronik Teknikeri",
"Elektronik Teknisyeni",
"Elektronik ve Haberleşme Mühendisi",
"Elektrostatik Boya Operatörü",
"Emlak ve Emlak Yönetimi Meslek Elemanı / Emlak Danışmanı",
"Emtia Borsası Meslek Elemanı",
"Endüstri Bitkileri Yetiştirme ve Değerlendirme Teknikeri",
"Endüstri Mühendisi",
"Endüstri Ürünleri Tasarımcısı",
"Endüstriyel Kalıpçı",
"Endüstriyel Kalıpçılık Teknikeri",
"Endüstriyel Mekanik Teknisyeni",
"Erkek Berberi (Erkek Kuaförü)",
"Erkek Terzisi",
"Et Endüstrisi Teknikeri",
"Et ve Et Ürünleri İşletmecisi",
"e-Ticaret Meslek Elemanı",
"Etnolog",
"Ev Cihazları Teknikeri",
"Ev Ekonomisti",
"Ev Tekstil Konfeksiyon Teknisyeni",
"Farmakolog",
"Felsefe Grubu Öğretmeni",
"Felsefeci",
"Fen Bilgisi Öğretmeni",
"Fermantasyon Teknikeri",
"Fırıncı",
"Fidan Yetiştirme Teknikeri",
"Finans Uzmanı",
"Fizik Mühendisi",
"Fizik Öğretmeni",
"Fizikçi",
"Fiziki Antropolog",
"Fizyoterapist",
"Fon Yöneticisi",
"Fora, Freze ve Gazumacı",
"Forklift Operatörü",
"Fotoğraf Sanatçısı",
"Fotoğrafçı",
"Fotoğrafçılık Teknikeri",
"Frezeci",
"Gazete Muhabiri",
"Gazetecilik ve Halkla İlişkiler Öğretmeni",
"Gemi Elektroniği ve Haberleşme Teknisyeni",
"Gemi İnşa Teknisyeni",
"Gemi İnşaatı Mühendisi",
"Gemi Makineleri Mühendisi",
"Gemi Makineleri Teknikeri / Makine Zabiti",
"Gemi Makineleri Teknisyeni",
"Gemi ve Deniz Yapıları Mühendisi",
"Gıda Mühendisi",
"Gıda Teknikeri",
"Gıda Teknolojisi Teknisyeni",
"Giyim / Hazır Giyim / Moda Tasarımı Öğretmeni",
"Giyim Endüstrisi Öğretmeni",
"Giyim Ve Giyim Aksesuarları Satış Elemanı",
"Görme Engelliler Sınıf Öğretmeni",
"Görsel İletişim Tasarımcısı",
"Grafik Teknikeri",
"Grafik Teknisyeni",
"Gümrük İşletme Meslek Elemanı",
"Güverte Teknikeri / Uzakyol Güverte Zabiti",
"Güzellik Uzmanı",
"Haberleşme Cihazları Bakım ve Onarımcısı",
"Haddeci",
"Hakim ( Yargıç )",
"Halı Dokuyucu (Otomatik Tezgah)",
"Halı Ve Kilim Teknikeri",
"Halkbilimci (Folklorcu)",
"Halkla İlişkiler ve Tanıtım Elemanı",
"Harita Kadastro Teknikeri",
"Harita Kadastro Teknisyeni",
"Harita Teknikeri",
"Hastane Yönetimi ve Organizasyonu Meslek Elemanı",
"Havacılık / Uçak Mühendisi",
"Hayvan Yetiştiriciliği ve Sağlığı Teknikeri",
"Hazır Giyim Teknikeri",
"Hemşire",
"Heykeltraş",
"Hızarcı",
"Hidrojeoloji Mühendisi",
"Hidrolik-Pnömatik Teknisyeni",
"Hidroterapi Teknikeri",
"Hukuk Sekreteri",
"İç Mekan Tasarımı Teknisyeni",
"İç Mimar - *Mimarlık",
"İklimlendirme ve Soğutma Teknikeri",
"İmam Hatip Lisesi Meslek Dersleri Öğretmeni",
"İnfaz ve Koruma Memuru (Gardiyan)",
"İnsan Kaynakları Meslek Elemanı",
"İnsan Kaynakları Uzmanı (Yöneticisi)",
"İnşaat Malzemeleri Satış Elemanı",
"İnşaat Mühendisi",
"İnşaat Teknisyeni",
"İpekböceği Teknikeri",
"İplik Teknisyeni",
"İstatistikçi",
"İş Eğitimi (İş ve Teknik Eğitim) Öğretmeni",
"İş Makineleri Tamircisi",
"İş Makineleri Teknikeri",
"İş Sağlığı ve Güvenliği Teknikeri",
"İş ve Uğraşı Terapisi Teknikeri",
"İşitme Engelliler Sınıf Öğretmeni",
"İşletme Meslek Elemanı",
"İşletme Mühendisi",
"İşletmeci",
"İtfaiyecilik ve Yangın Güvenliği Teknikeri",
"İthalat - İhracat Meslek Elemanı",
"Jeodezi ve Fotogrametri Mühendisi",
"Jeofizik Mühendisi",
"Jeoloji Mühendisi",
"Jeomorfolog",
"Jeoteknik Teknikeri",
"Kabin Memuru",
"Kadın Giysi Tasarımı Teknisyeni",
"Kadın Terzisi",
"Kağıt Teknikeri",
"Kalıp Öğretmeni",
"Kalıp Teknisyeni (Tekstil Konfeksiyon)",
"Kalıpçı",
"Kalıpçılık Teknikeri",
"Kalite Kontrol Teknisyeni (Tekstil Konfeksiyon)",
"Kalorifer Ateşcisi",
"Kaloriferci",
"Kameraman",
"Kaporta Tamircisi",
"Karo-Fayans Döşeyicisi",
"Kasiyer",
"Kat Görevlisi",
"Kaymakam",
"Kaynak Teknikeri",
"Kaynakçı",
"Kepçeli Araç Operatörü",
"Kırtasiye ve Kitap Satış Elemanı",
"Kimya Mühendisi",
"Kimya Öğretmeni",
"Kimya Teknikeri",
"Kimya Teknisyeni",
"Kimyager",
"Konfeksiyon Makineleri Bakım ve Onarım Teknisyeni",
"Kontrol Sistemleri Teknikeri",
"Kontrol ve Enstrümantasyon Teknolojisi Teknisyeni",
"Kooperatifçilik Meslek Elemanı",
"Kozmetik Teknikeri",
"Kuaförlük-Cilt Bakımı ve Güzellik Bilgisi Öğretmeni",
"Kule Vinç Operatörü",
"Kuru Temizlemeci",
"Kuyumcu",
"Kütüphaneci",
"Laboratuar Teknisyeni",
"Lastik Teknikeri",
"Maden Mühendisi",
"Maden Teknikeri",
"Mahalli İdareler Meslek Elemanı",
"Makastar",
"Makine / Tesviye / Kalıp Öğretmeni",
"Makine Mühendisi - Makine Mühendisliği",
"Makine Resim Konstrüksiyon Teknikeri",
"Makine Ressamı",
"Makine Ressamlığı Öğretmeni",
"Makine Teknisyeni (Tarım)",
"Makine Yağları ve Yağlama Teknikeri",
"Makineci (Dikiş)",
"Makinist (Demiryolu)",
"Maliye Meslek Elemanı",
"Manikürcü - Pedikürcü",
"Manken",
"Mantar Teknikeri",
"Marangoz",
"Matbaa Öğretmeni",
"Matbaa Teknikeri",
"Matbaa Teknisyeni",
"Matbaacı (Genel)",
"Matematik Mühendisi",
"Matematik Öğretmeni",
"Matematikçi",
"Mekatronik Teknisyeni",
"Mermer Teknikeri",
"Mermerci ve Süsleme Taşçısı",
"Metal İşleri Öğretmeni",
"Metal İşleri Teknikeri",
"Metal İşleri Teknisyeni",
"Metal Levha İşlemecisi",
"Metal Mamulleri Montaj İşçisi",
"Metalürji Teknisyeni",
"Metalürji ve Malzeme Mühendisi",
"Meteoroloji Mühendisi",
"Meyve ve Sebze İşleme Teknikeri",
"Meyve ve Sebze Satış Elemanı",
"Mikroteknoloji Teknisyeni",
"Mimar - Mimarlık",
"Mobilya Dekorasyon Teknisyeni",
"Mobilya Döşemecisi",
"Mobilya İmalatçısı",
"Mobilya Satış Elemanı",
"Mobilya Üst Yüzey İşlemcisi",
"Mobilya ve Dekorasyon Öğretmeni",
"Mobilya ve Dekorasyon Teknikeri",
"Moda Tasarım Teknisyeni",
"Moda Tasarımı Öğretmeni",
"Model Öğretmeni",
"Modelci (Makine Modelcisi)",
"Modelci (Plastik)",
"Moleküler Biyoloji ve Genetikçi (Moleküler Biyolog)",
"Motor (Otomotiv) Öğretmeni",
"Motor Teknisyeni",
"Motor Yenileştirmecisi (Motor Rektifiyecisi)",
"Motosiklet Tamircisi",
"Mozaikçi",
"Muhasebe Grubu Öğretmeni",
"Müfettiş",
"Müftü",
"Mütercim (Çevirmen)",
"Müzik Aleti (Çalgı) Yapımcısı",
"Müzik Öğretmeni",
"Nakış Öğretmeni",
"Noter",
"Nükleer Enerji Mühendisi",
"Odyometrist",
"Ofset Baskıcı",
"Okul Öncesi Öğretmeni",
"Opera Sanatçısı",
"Optisyen",
"Orman Endüstri Mühendisi",
"Orman Mühendisi",
"Ortopedi Teknisyeni",
"Oto Bakım-Onarımcısı (Oto-Motor Tamircisi)",
"Oto Boya Karoseri Doğrultma Teknikeri",
"Oto Boyacısı",
"Oto Döşemecisi",
"Oto Elektrikçisi",
"Oto Yedek Parça Satış Elemanı",
"Otobüs Şoförü (Kaptan)",
"Otomatik Kumanda Teknisyeni",
"Otomotiv Mühendisi",
"Otomotiv Teknikeri",
"Overlokçu",
"Öğretmenlik Meslek Bilgisi Dersleri Öğretmeni",
"Ön Büro Elemanı (Otel Resepsiyoncusu)",
"Ön Düzen ve Balans Ayarcısı",
"Örme Teknikeri",
"Örme Teknisyeni",
"Pamuk Eksperi ve İplikçilik Teknikeri",
"Pamuk Pazarlama ve İplikçilik Teknikeri",
"Pancar Yetiştiriciliği ve Şeker Teknikeri",
"Parke Döşemecisi",
"Pastacı",
"Patoloji Laboratuvar Teknikeri",
"Perakende Satış Elemanı (Tezgahtar)",
"Petro-Kimya Teknisyeni",
"Petrol ve Doğal Gaz Mühendisi",
"Peyzaj Mimarı",
"Peyzaj Teknikeri",
"Peyzaj Uygulama ve Süs Bitkileri Teknikeri",
"Pilot",
"Plastik Doğramacı",
"Plastik İşleme Teknisyeni",
"Plastik İşlemeci",
"Plastik Sanatlar Teknisyeni",
"Polis Memuru",
"Pratisyen Hekim (Tıp Doktoru)",
"Protez ve Ortez Teknikeri",
"Psikolog",
"Radyo - TV Teknisyeni",
"Radyo Televizyon Muhabiri",
"Radyo ve Televizyon Tamircisi",
"Radyoloji - Radyoterapi Teknikeri",
"Radyoloji (Röntgen) Teknisyeni",
"Radyo-Televizyon Program Yapımcısı (Prodüktör)",
"Radyo-TV Yayımcılığı Teknikeri",
"Rafineri ve Petrokimya Teknikeri",
"Rehber Öğretmen (Psikolojik Danışman)",
"Reklam Tabelacısı",
"Reklamcı",
"Remayözcü",
"Reprezant (İlaç Tanıtımı Elemanı)",
"Reprodüksiyon ve Klişe Teknisyeni",
"Reprodüksiyon ve Klişe Teknisyeni",
"Resim / Grafik Öğretmeni",
"Resim / Resim-İş Öğretmeni",
"Ressam",
"Restorasyon Teknikeri",
"Restorasyon Teknisyeni",
"Saat Tamircisi",
"Sac İşçisi",
"Sağlık Eğitimcisi",
"Sağlık Kurumları İşletmecisi",
"Sağlık Memuru",
"Sağlık Yöneticisi",
"Sahne ve Gösteri Sanatları Yöneticisi",
"Sanat Tarihçisi",
"Sanat Tarihi Öğretmeni",
"Sanayi Boyacılığı ve Uygulama Teknisyeni",
"Satış Yönetimi Meslek Elemanı",
"Savcı",
"Sayacı",
"Sebze Üretim Teknikeri",
"Sekreterlik Grubu Öğretmeni",
"Seracılık Teknikeri",
"Seramik Öğretmeni",
"Seramik Teknikeri",
"Seramik Teknisyeni",
"Serbest Muhasebeci",
"Serbest Muhasebeci-Mali Müşavir",
"Serigraf",
"Servis Elemanı (Garson)",
"Seyahat İşletmeciliği Meslek Elemanı",
"Seyahat İşletmeciliği ve Turizm Rehberliği Öğretmeni",
"Seyahat İşletmecisi",
"Seyahat Servis Elemanı (Otobüs / Tren)",
"Seyis",
"Sıcak Demirci",
"Sınıf Öğretmeni",
"Sıvacı",
"Sigortacılık Meslek Elemanı",
"Silindir Operatörü",
"Sistem Mühendisi",
"Soğuk Demirci",
"Soğutma ve İklimlendirme Teknisyeni",
"Soğutmacı ve Havalandırmacı (İklimlendirme)",
"Sondaj Teknikeri",
"Sosyal Bilgiler Öğretmeni",
"Sosyal Çalışmacı (Sosyal Hizmet Uzmanı)",
"Sosyolog",
"Spiker",
"Spor Antrenörü (Spor Eğitimcisi)",
"Spor Hakemi",
"Spor Yöneticisi",
"Stilist",
"Su Ürünleri Teknikeri",
"Su Ürünleri Teknisyeni",
"Sulama Teknikeri",
"Süt ve Ürünleri Teknikeri",
"Takı Teknikeri",
"Tapu Kadastro Teknikeri",
"Tarım Alet ve Makineleri Teknikeri",
"Tarım Ürünleri Satış Elemanı",
"Tarımsal Kooperatifcilik Meslek Elemanı",
"Tarih Öğretmeni",
"Tarihçi",
"Taş ve Metal İşleme Teknikeri",
"Taşçı",
"Taşlama ve Alet Bilemecisi",
"Tekstil Baskı Teknikeri",
"Tekstil Kalite Kontrol Teknisyeni",
"Tekstil Mühendisi",
"Tekstil Öğretmeni",
"Tekstil Tasarım Teknisyeni",
"Tekstil Terbiye Teknisyeni",
"Telekomünikasyon (Haberleşme) Teknikeri",
"Telekomünikasyon (Haberleşme) Teknisyeni",
"Telekomünikasyon Mühendisi",
"Teleks Operatörü",
"Terzi (Abiye-Gelinlik)",
"Tesisat Öğretmeni",
"Tesviyeci",
"Tıbbi Araçlar Satış Elemanı",
"Tıbbi Dökümantasyoncu ve Sekreter",
"Tıbbi Laboratuar Teknikeri",
"Tıp Sekreteri",
"Ticaret ve Yönetim Meslek Elemanı",
"Tipo Baskıcı",
"Tiyatro Eleştirmeni ve Dramaturg",
"Tiyatro Oyuncusu",
"Tohumculuk Teknikeri",
"Tornacı",
"Tramvay / Metro Sürücüsü (Vatman)",
"Trikotaj Öğretmeni",
"Trikotajcı",
"Tur Operatörü",
"Turist Rehberi",
"Turizm ve Otel İşletmeciliği Meslek Elemanı",
"Turizm ve Otelcilik Grubu Öğretmeni",
"Türk Dili ve Edebiyatı Öğretmeni",
"Türkçe Öğretmeni",
"Türkolog",
"Uçak Motorları Bakım Onarım Teknisyeni",
"Ulaştırma Teknikeri",
"Uluslararası Ticaret Yönetimi Meslek Elemanı",
"Un Üretim Teknikeri",
"Uzay Mühendisi",
"Üretim Mühendisi",
"Üstün Zekalılar Öğretmeni",
"Ütücü",
"Vargel ve Planyacı",
"Vergi Denetmeni",
"Veteriner Hekim",
"Veteriner Sağlık Teknisyeni",
"Vitrin Kuyumcusu",
"Yabancı Dil Öğretmeni",
"Yağ Teknikeri",
"Yalıtım Teknikeri",
"Yapı Öğretmeni",
"Yapı Ressamı",
"Yapı Ressamlığı Öğretmeni",
"Yapı Yalıtımcısı",
"Yapı/ Yapı Ressamlığı/ Harita ve Kadastro Öğretmeni",
"Yazar",
"Yazılım Mühendisi",
"Yeminli Mali Müşavir",
"Yer Hostesi",
"Yiyecek İçecek İşletmeciliği Meslek Elemanı",
"Yönetici Sekreteri",
"Yönetim Bilişim Sistemleri Uzmanı",
"Zihin Engelliler Sınıf Öğretmeni",
"Ziraat Makineleri Tamircisi",
"Zoolog"]

pozisyonlar =[
"Ağ Yöneticisi",
"Analist",
"Asistan",
"Aşcı Başı",
"Atölye Şefi",
"Baş Formen",
"Başkan",
"Başkan Yardımcısı",
"Bilgisayar Programcısı ",
"Çağrı Merkezi Yöneticisi",
"Çırak",
"Danışman",
"Donanım Uzmanı",
"Ekip Lideri",
"Eksper",
"Formen",
"Genel Müdür",
"Genel Müdür Yardımcısı",
"Grafiker",
"Güvenlik Görevlisi",
"Haberleşme Müdürü",
"Hemşire",
"İdari İşler Müdürü",
"İşçi",
"Kalfa",
"Kalite Güvence Müdürü",
"Kasiyer",
"Koordinatör",
"Memur",
"Muavin",
"Multimedya Tasarımcısı",
"Müdür",
"Müdür Yardımcısı",
"Mühendis",
"Müşteri Temsilcisi",
"Nakliyat Müdürü",
"Ofis Yöneticisi",
"Operatör",
"Öğretmenlik",
"Ön Büro Elemanı",
"Proje Yöneticisi",
"Rehber",
"Satınalma Sorumlusu",
"Satış Danışmanı",
"Satış Temsilcisi",
"Stok Kontrol Müdürü",
"Stratejik Planlama Müdürü",
"Süpervizör",
"Şantiye Şefi",
"Şef",
"Şef Yardımcısı",
"Şube Müdürü",
"Şube Müdürü Yardımcısı",
"Teknik Destek Uzmanı",
"Tekniker",
"Teknisyen",
"Ticaret Müdürü",
"Usta",
"Usta Başı",
"Uzman",
"Veritabanı Uzmanı",
"Veritabanı Yöneticisi",
"Web Tasarımcısı",
"Yazılım Geliştirici",
"Yazılım Geliştirme Uzmanı",
"Yazılım Tasarım Uzmanı",
"Yönetici",
"Yönetici Adayı",
"Yönetici Yardımcısı"]