milletler = ["Danimarkalı","İngiliz","Estonyalı","Finlandiyalı","İzlandalı",
"İrlandalı","Letonyalı","Litvanyalı","Kuzey İrlandalı","Norveçli","İskoç",
"İsveçli","İngiliz","Galli","Avusturyalı","Belçikalı","Fransız","Alman",
"Hollandalı","İsviçreli","Arnavut","Hırvat","Kıbrıslı","Yunanlı","İtalyan",
"Portekizli","Sırp","Sloven","İspanyol","Belaruslu","Bulgar","Çek","Macar",
"Polonyalı","Romanyalı","Rus","Slovak","Ukraynalı","Kanadalı","Meksikalı",
"Amerikalı","Kübalı","Guatemalalı","Jamaikalı","Arjantinli","Kürt","Bolivyalı",
"Brezilyalı","Şilili","Kolombiyalı","Ekvadorlu","Paraguaylı","Perulu","Uruguaylı",
"Venezuellalı","Gürcü","İranlı","Iraklı","İsrailli","Ürdünlü","Kuveytli",
"Lübnanlı","Filistinli","Suudi Arabistanlı","Suriyeli","Türk","Yemenli","Afgan",
"Bangladeşli","Hintli","Kazak","Nepalli","Pakistanlı","Sri lankalı","Çinli",
"Japon","Moğol","Kuzey Koreli","Güney Koreli","Tayvanlı","Kamboçyalı","Endonezyalı",
"Laoslu","Malezyalı","Burmalı","Filipinli","Singapurlu","Tay","Vietnamlı",
"Avusturalyalı","Fijili","Yeni Zelandalı","Cezayirli","Mısırlı","Ganalı",
"Fildişi Sahilli","Libyalı","Faslı","Nijeryalı","Tunuslu","Etopyalı","Kenyalı",
"Somalili","Sudanlı","Tanzanyalı","Ugandalı","Angolalı","Botsvanalı","Kongolu",
"Madagaskarlı","Mozambikli","Namibyalı","Güney Afrikalı","Zambiyalı","Zimbabveli"]