# Generated by Django 2.2.10 on 2020-02-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duyurular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DuyuruKodu', models.CharField(max_length=10)),
                ('Baslik', models.CharField(max_length=50)),
                ('Icerik', models.TextField()),
                ('KullaniciGrubu', models.CharField(max_length=10, null=True)),
                ('Kullanici', models.CharField(max_length=10)),
                ('Durumu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gorevler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GorevKodu', models.CharField(max_length=10)),
                ('Baslik', models.CharField(max_length=50)),
                ('Icerik', models.TextField()),
                ('KullaniciGrubu', models.CharField(max_length=10, null=True)),
                ('Kullanici', models.CharField(max_length=10)),
                ('Durumu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hatirlatmalar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HatirlatmaKodu', models.CharField(max_length=10)),
                ('Baslik', models.CharField(max_length=50)),
                ('Icerik', models.TextField()),
                ('KullaniciGrubu', models.CharField(max_length=10, null=True)),
                ('Kullanici', models.CharField(max_length=10)),
                ('Durumu', models.IntegerField()),
            ],
        ),
    ]
